version: '3'

services:
  # nginx Web Server
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public
    depends_on:
      - php

  # PHP-FPM (app)
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    restart: always
    expose:
      - 9000
    volumes:
      - ./.docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      WAIT_HOSTS: mysql:3306
      DB_HOST: mysql
      DB_NAME: app_db
      DB_USER: app_user
      DB_PASS: app_pass
    depends_on:
      - mysql

  # MySQL Server
  mysql:
    image: mariadb:10.4
    restart: always
    expose:
      - 3306
    volumes:
      - app-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: app_pass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass

volumes:
  app-data:
